
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionEntreprise;
import java.sql.*;
import java.lang.Class.*;

/**
 *
 * @author p1205670
 */
public class AcceuilGestionnaire extends javax.swing.JFrame {

    /**
     * Creates new form AcceuilGestionnaire
     */
    private Object makeObj(final String item)  {
     return new Object() { public String toString() { return item; } };
    }
    
    // Ouvre une connexion stockée dans la variable conn
    public void openConnection() throws java.sql.SQLException {
        //   String userid = "nom_utilisateur";   // A MODIFIER
        //   String password = "#########";  // A MODIFIER
        //   String URL = "jdbc:oracle:thin:@iuta.univ-lyon1.fr:1521:orcl";	// Adresse de l'hote distant

        String userid = "p0907867";   // A MODIFIER
        String password = "iut2012";  // A MODIFIER
        String URL = "jdbc:oracle:thin:@iuta.univ-lyon1.fr:1521:orcl";	// Adresse de l'hote distant
        java.sql.DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        conn = java.sql.DriverManager.getConnection(URL, userid, password);

        if (conn == null) {
            Model.addElement("Probleme de connection.");
            System.exit(1);
        }
    }
    
    public void closeConnection() throws java.sql.SQLException {
        conn.close();	// Fermeture de la connection
    }
    
    public AcceuilGestionnaire() {
        initComponents();
        setLocation(200, 150);
        
        // remplir listes
        String noment;
        
        try {
            openConnection();
            java.sql.Statement requete = conn.createStatement();
            java.sql.ResultSet resulent = requete.executeQuery(
            "select NOMENT from ENTREPRISE");
            while (resulent.next()) {
                noment = resulent.getString(1);
                comboEnt.addItem(makeObj(noment));
            }
            resulent.close();
            requete.close();
            closeConnection();
        } catch (java.sql.SQLException e) {
            Model.addElement("Erreur execution requete " + e.getMessage());
        }
        try {
            openConnection();
            java.sql.Statement requete = conn.createStatement();
            java.sql.ResultSet resuletu = requete.executeQuery(
            "select NOMETUDE from ETUDE");
            while (resuletu.next()) {
                noment = resuletu.getString(1);
                listeetude.addItem(makeObj(noment));
            }
            resuletu.close();
            requete.close();
            closeConnection();
        } catch (java.sql.SQLException e) {
            Model.addElement("Erreur execution requete " + e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AcceuilGestionnaire = new javax.swing.JTabbedPane();
        Acceuil = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Entreprise = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        affEnt = new javax.swing.JList();
        comboEnt = new javax.swing.JComboBox();
        afficherEnt = new javax.swing.JButton();
        créerEnt = new javax.swing.JButton();
        modifierEnt = new javax.swing.JButton();
        Etude = new javax.swing.JPanel();
        listeetude = new javax.swing.JComboBox();
        afficheretude = new javax.swing.JButton();
        modifieretude = new javax.swing.JButton();
        creeretude = new javax.swing.JButton();
        detailetude = new javax.swing.JScrollPane();
        etude = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        Etudiant = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\nChoisisez l'onglet ...");
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setText("Fermer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fin(evt);
            }
        });

        javax.swing.GroupLayout AcceuilLayout = new javax.swing.GroupLayout(Acceuil);
        Acceuil.setLayout(AcceuilLayout);
        AcceuilLayout.setHorizontalGroup(
            AcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcceuilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        AcceuilLayout.setVerticalGroup(
            AcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcceuilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AcceuilGestionnaire.addTab("Acceuil", Acceuil);

        jScrollPane1.setViewportView(affEnt);

        afficherEnt.setText("afficher");
        afficherEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherEnt(evt);
            }
        });

        créerEnt.setText("créer");
        créerEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerEnt(evt);
            }
        });

        modifierEnt.setText("modifier");
        modifierEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifEnt(evt);
            }
        });

        javax.swing.GroupLayout EntrepriseLayout = new javax.swing.GroupLayout(Entreprise);
        Entreprise.setLayout(EntrepriseLayout);
        EntrepriseLayout.setHorizontalGroup(
            EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntrepriseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(EntrepriseLayout.createSequentialGroup()
                        .addComponent(comboEnt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(afficherEnt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modifierEnt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(créerEnt)))
                .addContainerGap())
        );
        EntrepriseLayout.setVerticalGroup(
            EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntrepriseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(créerEnt)
                    .addComponent(afficherEnt)
                    .addComponent(comboEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifierEnt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        AcceuilGestionnaire.addTab("Entreprise", Entreprise);

        afficheretude.setText("Afficher");
        afficheretude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficheretude(evt);
            }
        });

        modifieretude.setText("Gérer les participants");
        modifieretude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifieretude(evt);
            }
        });

        creeretude.setText("Creer");
        creeretude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creeretude(evt);
            }
        });

        detailetude.setViewportView(etude);

        jButton2.setText("Valider");

        javax.swing.GroupLayout EtudeLayout = new javax.swing.GroupLayout(Etude);
        Etude.setLayout(EtudeLayout);
        EtudeLayout.setHorizontalGroup(
            EtudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EtudeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EtudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailetude)
                    .addGroup(EtudeLayout.createSequentialGroup()
                        .addComponent(listeetude, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(afficheretude)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creeretude)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EtudeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifieretude)
                .addGap(58, 58, 58))
        );
        EtudeLayout.setVerticalGroup(
            EtudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EtudeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EtudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listeetude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(afficheretude)
                    .addComponent(creeretude)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifieretude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(detailetude, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        AcceuilGestionnaire.addTab("Etude", Etude);

        javax.swing.GroupLayout EtudiantLayout = new javax.swing.GroupLayout(Etudiant);
        Etudiant.setLayout(EtudiantLayout);
        EtudiantLayout.setHorizontalGroup(
            EtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        EtudiantLayout.setVerticalGroup(
            EtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        AcceuilGestionnaire.addTab("Etudiant", Etudiant);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AcceuilGestionnaire)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AcceuilGestionnaire)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creerEnt(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerEnt
        Entreprise e= new Entreprise();
        ModifEntreprise bdd =new ModifEntreprise(this, true, e);
        bdd.setLocation(500, 400);
        bdd.setVisible(true);
        
        //on ajoute la nouvelle ligne à la base :
        
        
    }//GEN-LAST:event_creerEnt

    private void afficherEnt(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherEnt
        
        Model.clear();
        
        
        
    }//GEN-LAST:event_afficherEnt

    private void fin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fin
        int rep = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "voulez-vous réellement vous arrêter ?", 
                "fin de l'application", 
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (rep == javax.swing.JOptionPane.YES_OPTION){
            dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_fin

    private void modifEnt(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifEnt
        Entreprise e= new Entreprise();
        
        ModifEntreprise bdd =new ModifEntreprise(this, true, e);
        bdd.setLocation(500, 400);
        bdd.setVisible(true);
        
        //après modification :

    }//GEN-LAST:event_modifEnt

    private void afficheretude(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficheretude

    }//GEN-LAST:event_afficheretude

    private void modifieretude(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifieretude
        Etude e = new Etude("etude 1");
       // ModifEtude bdd = new ModifEtude(this, true, e);
    }//GEN-LAST:event_modifieretude

    private void creeretude(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creeretude
        // TODO add your handling code here:
    }//GEN-LAST:event_creeretude

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceuilGestionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceuilGestionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceuilGestionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceuilGestionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcceuilGestionnaire().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acceuil;
    private javax.swing.JTabbedPane AcceuilGestionnaire;
    private javax.swing.JPanel Entreprise;
    private javax.swing.JPanel Etude;
    private javax.swing.JPanel Etudiant;
    private javax.swing.JList affEnt;
    private javax.swing.JButton afficherEnt;
    private javax.swing.JButton afficheretude;
    private javax.swing.JComboBox comboEnt;
    private javax.swing.JButton creeretude;
    private javax.swing.JButton créerEnt;
    private javax.swing.JScrollPane detailetude;
    private javax.swing.JList etude;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox listeetude;
    private javax.swing.JButton modifierEnt;
    private javax.swing.JButton modifieretude;
    // End of variables declaration//GEN-END:variables
private javax.swing.DefaultListModel Model = new javax.swing.DefaultListModel();
private java.sql.Connection conn;

}
