/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionEntreprise;

/**
 *
 * @author p1205670
 */
public class CreationEtude extends javax.swing.JDialog {

    /**
     * Creates new form CreationEtude
     */
    
    private Object makeObj(final String item)  {
     return new Object() {@Override
 public String toString() { return item; } };
    }
    
    // Ouvre une connexion stockée dans la variable conn
    public void openConnection() throws java.sql.SQLException {
        //   String userid = "nom_utilisateur";   // A MODIFIER
        //   String password = "#########";  // A MODIFIER
        //   String URL = "jdbc:oracle:thin:@iuta.univ-lyon1.fr:1521:orcl";	// Adresse de l'hote distant

        String userid = "p0907867";   // A MODIFIER
        String password = "iut2012";  // A MODIFIER
        String URL = "jdbc:oracle:thin:@iuta.univ-lyon1.fr:1521:orcl";	// Adresse de l'hote distant
        java.sql.DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        conn = java.sql.DriverManager.getConnection(URL, userid, password);

        if (conn == null) {
            Model.addElement("Probleme de connection.");
            System.exit(1);
        }
    }
    
    public void closeConnection() throws java.sql.SQLException {
        conn.close();	// Fermeture de la connection
    }
    
    public CreationEtude(java.awt.Frame parent, boolean modal, Etude e) {
        super(parent, modal);
        initComponents();
        CreationEtude.e = e;
        nom = e.nom_etude;
        dureeet = e.duree;
        datefin = e.datefin;
        ent = e.ent;
        
        text_intitule.setText(e.nom_etude);
        text_duree.setText(Integer.toString(e.duree));
        text_datefin.setText(e.datefin);
        
        String nom_ent;
        int id_ent;
        
        try {
            openConnection();
            java.sql.Statement requete = conn.createStatement();
            java.sql.ResultSet resul = requete.executeQuery("select * from ENTREPRISE");
            while (resul.next()) {
                nom_ent = resul.getString(2);
                id_ent = resul.getInt(1);
                listeent.addItem(makeObj(id_ent + " -- " + nom_ent));
            }
            resul.close();
            requete.close();
            closeConnection();
        } catch (java.sql.SQLException exc) {
            Model.addElement("Erreur execution requete " + exc.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        intitule_et = new javax.swing.JLabel();
        duree_et = new javax.swing.JLabel();
        datefin_et = new javax.swing.JLabel();
        text_intitule = new javax.swing.JTextField();
        text_duree = new javax.swing.JTextField();
        jours = new javax.swing.JRadioButton();
        semaines = new javax.swing.JRadioButton();
        mois = new javax.swing.JRadioButton();
        text_datefin = new javax.swing.JTextField();
        listeent = new javax.swing.JComboBox();
        ent_et = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Module de création d'une étude");

        intitule_et.setText("Intitulé : ");

        duree_et.setText("Durée : ");

        datefin_et.setText("Date de fin prévue : ");

        text_duree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verifduree(evt);
            }
        });

        buttonGroup1.add(jours);
        jours.setText("jours");

        buttonGroup1.add(semaines);
        semaines.setText("semaines");

        buttonGroup1.add(mois);
        mois.setText("mois");

        listeent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listeent(evt);
            }
        });

        ent_et.setText("Entreprise : ");

        jButton4.setText("(optionel) creer entreprise");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(datefin_et)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_datefin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(duree_et)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_duree, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jours)
                                .addGap(18, 18, 18)
                                .addComponent(semaines)
                                .addGap(18, 18, 18)
                                .addComponent(mois))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ent_et)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listeent, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(intitule_et)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_intitule, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intitule_et)
                    .addComponent(text_intitule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duree_et)
                    .addComponent(text_duree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jours)
                    .addComponent(semaines)
                    .addComponent(mois))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datefin_et)
                    .addComponent(text_datefin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ent_et)
                    .addComponent(listeent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listeent(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listeent
        noment = evt.getItem( ).toString( );
    }//GEN-LAST:event_listeent

    private void verifduree(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verifduree
        Character c = evt.getKeyChar();
        
        if (!(Character.isDigit(c))) {
           evt.consume();
        }
    }//GEN-LAST:event_verifduree

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel datefin_et;
    private javax.swing.JLabel duree_et;
    private javax.swing.JLabel ent_et;
    private javax.swing.JLabel intitule_et;
    private javax.swing.JButton jButton4;
    private javax.swing.JRadioButton jours;
    private javax.swing.JComboBox listeent;
    private javax.swing.JRadioButton mois;
    private javax.swing.JRadioButton semaines;
    private javax.swing.JTextField text_datefin;
    private javax.swing.JTextField text_duree;
    private javax.swing.JTextField text_intitule;
    // End of variables declaration//GEN-END:variables
    private javax.swing.DefaultListModel Model = new javax.swing.DefaultListModel();
    private java.sql.Connection conn;

    String nom;
    int dureeet;
    String datefin;
    Entreprise ent;
    String noment;
    int nbjour, nbsemaine, nbmois;
    
    static Etude e;
}
