/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionEntreprise;

/**
 *
 * @author p1205670
 */
public class gestionFrais extends javax.swing.JDialog {

    /**
     * Creates new form gestionFrais
     */
    private Object makeObj(final String item)  {
     return new Object() { public String toString() { return item; } };
    }
    
    public void openConnection() throws java.sql.SQLException {
        //   String userid = "nom_utilisateur";   // A MODIFIER
        //   String password = "#########";  // A MODIFIER
        //   String URL = "jdbc:oracle:thin:@iuta.univ-lyon1.fr:1521:orcl";	// Adresse de l'hote distant

        String userid = "p0907867";   // A MODIFIER
        String password = "iut2012";  // A MODIFIER
        String URL = "jdbc:oracle:thin:@iuta.univ-lyon1.fr:1521:orcl";	// Adresse de l'hote distant
        java.sql.DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        conn = java.sql.DriverManager.getConnection(URL, userid, password);

        if (conn == null) {
            ModelInfo.addElement("Probleme de connection.");
            System.exit(1);
        }
    }
    
    public void closeConnection() throws java.sql.SQLException {
        conn.close();	// Fermeture de la connection
    }
    
    public void rempirListEtude () {
        String Sreqlist;
        listEtude.removeAllItems();
        Sreqlist = "select * from ASSOCIATION join ETUDE "
                + "on ASSOCIATION.IDCONVENTION = ETUDE.IDCONVENTION "
                + "WHERE IDETUDIANT ="+idetudiant;
        
        try {
            listEtude.addItem("Selectionner l'étude à détailler");
            openConnection();
            java.sql.Statement reqlist = conn.createStatement();
            java.sql.ResultSet resullist = reqlist.executeQuery(Sreqlist);
            while (resullist.next()) {
                listEtude.addItem(makeObj(resullist.getInt("IDCONVENTION")+ " -- " +resullist.getString("NOMETUDE")));
            }
            
            reqlist.close();
            resullist.close();
            closeConnection();
        } catch (java.sql.SQLException e) {
            ModelInfo.addElement("Erreur execution requete " + e.getMessage());
            AffFrais.setModel(ModelInfo);
        }
    }
    
    public gestionFrais(java.awt.Frame parent, boolean modal, int idetudiant) {
        super(parent, modal);
        initComponents();
        gestionFrais.idetudiant = idetudiant;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listEtude = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        montant = new javax.swing.JTextField();
        enregistrementFrais = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AffFrais = new javax.swing.JList();
        listFrais = new javax.swing.JComboBox();
        rembourser = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Montant à enregistrer :");

        enregistrementFrais.setText("Enregistrer frais");
        enregistrementFrais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validation(evt);
            }
        });

        jScrollPane1.setViewportView(AffFrais);

        rembourser.setText("Rembourser");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(listEtude, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(montant, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(listFrais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rembourser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enregistrementFrais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listEtude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(montant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enregistrementFrais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listFrais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rembourser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validation(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validation
        Character c =evt.getKeyChar();
        
        if (!(Character.isDigit(c))) {
           evt.consume();
        }
    }//GEN-LAST:event_validation

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList AffFrais;
    private javax.swing.JButton enregistrementFrais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listEtude;
    private javax.swing.JComboBox listFrais;
    private javax.swing.JTextField montant;
    private javax.swing.JToggleButton rembourser;
    // End of variables declaration//GEN-END:variables
    static int idetudiant;
    private javax.swing.DefaultListModel ModelInfo = new javax.swing.DefaultListModel();
    private java.sql.Connection conn;
}
