/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionEntreprise;

import java.util.HashMap;

/**
 *
 * @author p1205670
 */
public class SuiviEtudiant extends javax.swing.JDialog {

    /**
     * Creates new form SuiviEtudiant
     */
    private Object makeObj(final String item)  {
     return new Object() { public String toString() { return item; } };
    }
    
    public void openConnection() throws java.sql.SQLException {
        //   String userid = "nom_utilisateur";   // A MODIFIER
        //   String password = "#########";  // A MODIFIER
        //   String URL = "jdbc:oracle:thin:@iuta.univ-lyon1.fr:1521:orcl";	// Adresse de l'hote distant

        String userid = "p0907867";   // A MODIFIER
        String password = "iut2012";  // A MODIFIER
        String URL = "jdbc:oracle:thin:@iuta.univ-lyon1.fr:1521:orcl";	// Adresse de l'hote distant
        java.sql.DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        conn = java.sql.DriverManager.getConnection(URL, userid, password);

        if (conn == null) {
            ModelInfo.addElement("Probleme de connection.");
            System.exit(1);
        }
    }
    
    public void closeConnection() throws java.sql.SQLException {
        conn.close();	// Fermeture de la connection
    }
    
    public void rempirListEtude () {
        String Sreqlist;
        listEtude.removeAllItems();
        Sreqlist = "select * from ASSOCIATION join ETUDE "
                + "on ASSOCIATION.IDCONVENTION = ETUDE.IDCONVENTION "
                + "WHERE IDETUDIANT ="+idetudiant;
        
        try {
            listEtude.addItem("Selectionner l'étude à détailler");
            openConnection();
            java.sql.Statement reqlist = conn.createStatement();
            java.sql.ResultSet resullist = reqlist.executeQuery(Sreqlist);
            while (resullist.next()) {
                conteneur detail = new conteneur();

                //on remplit la map avec les conteneur
                detail.setNbjours(resullist.getInt("NBJOURS"));
                detail.setStatus(resullist.getInt("STATUTETUDIANT"));
                detail.setNom_etude(resullist.getString("NOMETUDE"));
                detail.setIdconvention(resullist.getInt("IDCONVENTION"));
                listEtude.addItem(makeObj(detail.getIdconvention()+ " -- " +detail.getNom_etude()));
                ensemble.put(resullist.getInt("IDCONVENTION"), detail);
            
            }
            reqlist.close();
            resullist.close();
            closeConnection();
        } catch (java.sql.SQLException e) {
            ModelInfo.addElement("Erreur execution requete " + e.getMessage());
            affInfoEtude.setModel(ModelInfo);
        }
    }
    
    public SuiviEtudiant(java.awt.Frame parent, boolean modal,int idetudiant) {
        super(parent, modal);
        initComponents();
        SuiviEtudiant.idetudiant = idetudiant;
        rempirListEtude();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listEtude = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        affInfoEtude = new javax.swing.JList();
        retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listEtude.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                affEtude(evt);
            }
        });

        jScrollPane1.setViewportView(affInfoEtude);

        retour.setText("Retour");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(listEtude, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(retour)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listEtude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(retour)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retour(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour
        setVisible(false);
    }//GEN-LAST:event_retour

    private void affEtude(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_affEtude
        ModelInfo.clear();
        int id;
        String l;
        String [] t;
        conteneur etude;
        l = listEtude.getSelectedItem().toString();
        t = l.split(" ");
        if (!(Character.isDigit( t[0].charAt(0)))) {
            ModelInfo.addElement("sélectionner une étude");
            affInfoEtude.setModel(ModelInfo);
        }else {
            id = Integer.parseInt(t[0]);

            etude = ensemble.get(id);
            ModelInfo.addElement("Pour létude : "+etude.getNom_etude()+" l'élève était :"+etude.getStatus()+".");
            ModelInfo.addElement("Il a travailler : "+etude.getNbjours()+" jour(s).");
            ModelInfo.addElement("Pour un total de :"+etude.getIndemnite()+" € versé le : "+etude.getDate_paie()+".");
            affInfoEtude.setModel(ModelInfo);
        }
    }//GEN-LAST:event_affEtude

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList affInfoEtude;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listEtude;
    private javax.swing.JButton retour;
    // End of variables declaration//GEN-END:variables
    static int idetudiant;
    private javax.swing.DefaultListModel ModelInfo = new javax.swing.DefaultListModel();
    private java.sql.Connection conn;
    HashMap<Integer, conteneur> ensemble = new HashMap<>();
}
