/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionEntreprise;

import java.util.HashMap;

/**
 *
 * @author p1205670
 */
public class SuiviEtudiant extends javax.swing.JDialog {

    /**
     * Creates new form SuiviEtudiant
     */
    private Object makeObj(final String item)  {
     return new Object() { public String toString() { return item; } };
    }
    
    public void openConnection() throws java.sql.SQLException {
        //   String userid = "nom_utilisateur";   // A MODIFIER
        //   String password = "#########";  // A MODIFIER
        //   String URL = "jdbc:oracle:thin:@iuta.univ-lyon1.fr:1521:orcl";	// Adresse de l'hote distant

        String userid = "p0907867";   // A MODIFIER
        String password = "iut2012";  // A MODIFIER
        String URL = "jdbc:oracle:thin:@iuta.univ-lyon1.fr:1521:orcl";	// Adresse de l'hote distant
        java.sql.DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        conn = java.sql.DriverManager.getConnection(URL, userid, password);

        if (conn == null) {
            Model.addElement("Probleme de connection.");
            System.exit(1);
        }
    }
    
    public void closeConnection() throws java.sql.SQLException {
        conn.close();	// Fermeture de la connection
    }
    
    public void rempirListEtude () {
        String Sreqlist;
        conteneur detail = new conteneur();
        int idetude;
        listEtude.removeAllItems();
        Sreqlist = "select IDCONVENTION from ASSOCIATION WHERE IDETUDIANT ="+idetudiant+
                "join ETUDE on ASSOCIATION.IDCONVENTION = ETUDE.IDCONVENTION";
        try {
            openConnection();
            java.sql.Statement reqlist = conn.createStatement();
            java.sql.ResultSet resullist = reqlist.executeQuery(Sreqlist);
            while (resullist.next()) {
                
                //en cours : remplir la map avec les conteneur 
                
                detail.setNom_etude(resullist.getString("NOMETUDE"));
                idetude = resullist.getInt("IDCONVENTION");
                listEtude.addItem(makeObj(idetude+ " -- " +detail.getNom_etude()));
                
            
            }
            reqlist.close();
            resullist.close();
            closeConnection();
        } catch (java.sql.SQLException e) {
            Model.addElement("Erreur execution requete " + e.getMessage());
        }
    }
    
    public SuiviEtudiant(java.awt.Frame parent, boolean modal,int idetudiant) {
        super(parent, modal);
        initComponents();
        SuiviEtudiant.idetudiant = idetudiant;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listEtude = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        affEtude = new javax.swing.JList();
        retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(affEtude);

        retour.setText("Retour");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(listEtude, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(retour)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listEtude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(retour)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retour(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour
        setVisible(false);
    }//GEN-LAST:event_retour

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList affEtude;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listEtude;
    private javax.swing.JButton retour;
    // End of variables declaration//GEN-END:variables
    static int idetudiant;
    private javax.swing.DefaultListModel Model = new javax.swing.DefaultListModel();
    private java.sql.Connection conn;
    HashMap<Integer, conteneur> enssemble = new HashMap<>();
}
